import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import News from "~/components/News";
import AddPost from "~/components/AddPost";

interface Props {
  isAdmin: boolean;
}

export default function Home({ isAdmin }: Props) {
  const [addPost, setAddPost] = useState(false);
  const [posts, setPosts] = useState([]);

  const fetchPosts = async () => {
    await axios.get("/api/post").then((res) => {
      setPosts(res.data);
    });
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  return (
    <>
      <Head>
        <title>News | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen justify-center px-10">
        <div className="mt-16">
          <News posts={posts} />

          {isAdmin && (
            <div
              className="mt-5 w-full cursor-pointer rounded-lg bg-white py-2 shadow"
              onClick={() => setAddPost(true)}
            >
              <p className="text-center text-xl uppercase">Add post</p>
            </div>
          )}

          {addPost && (
            <AddPost setAddPost={setAddPost} fetchPosts={fetchPosts} />
          )}
        </div>
      </main>
    </>
  );
}
