import axios from "axios";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Profile from "~/components/Profile";

interface Props {
  user: string | null;
}

const Account = ({ user }: Props) => {
  const [users, setUsers] = useState([]);

  const fetchUsers = async () => {
    await axios.get("/api/user").then((res) => {
      setUsers(res.data);
    });
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  return (
    <>
      <Head>
        <title>News | Account</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`flex min-h-screen justify-center px-10`}>
        <div className="mt-16">
          <div className="flex h-full items-center">
            {user === null ? (
              <h1 className="text-xl">You are not registered yet!</h1>
            ) : (
              users.map(
                (dbUser: any) =>
                  dbUser.id === user && (
                    <div>
                      <Profile user={dbUser} fetchUsers={fetchUsers} />
                    </div>
                  ),
              )
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Account;
